# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# echo -n 'ansible' | ansible-vault encrypt_string --stdin-name 'ansible_password'
all:
  children:
    db:
      hosts:
        vm:
          ansible_host: 192.168.0.105
          ansible_user: ansible
          # ansible_password: ansible
          ansible_python_interpreter: /usr/bin/python3
          var1: value1
    vms:
      children:
        db: